name: Build

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Publish
      run: dotnet publish --no-restore
    - uses: actions/upload-artifact@v4
      with:
        name: mgxc2s
        path: build
